# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      token: ${{ secrets.SLACK_BOT_TOKEN }} 
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.9]

    steps:
#     - uses: actions/checkout@v3
#     - name: Set up Python ${{ matrix.python-version }}
#       uses: actions/setup-python@v3
#       with:
#         python-version: ${{ matrix.python-version }}
#     - name: Install dependencies
#       id: send-version-diff
#       run: |
#         python -m pip install --upgrade pip
#         pip install requests
#         pip install slackclient
#         python -c "import requests; import json; import versionDiff; thread_id = versionDiff.sendVersionDiffsToSlack( '${{ secrets.SLACK_BOT_TOKEN }}', '#test')"
#       working-directory: scripts
      
    - name: Send Failed Slack Message
      if: steps.send-version-diff.outcome != 'success'
      uses: archive/github-actions-slack@v2.4.0
      id: send-failed-message
      with:
        slack-function: send-message
        slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_TOKEN }}
        slack-optional-icon_emoji: ":fire:"
        slack-channel: C045T8PT056
        slack-text: Failed Stable API Test on -  https://github.com/sam-rtr/test/actions/runs/${{ github.run_id }} - Branch - ${{ github.HEAD_REF }}
